CREATE TABLE IF NOT EXISTS players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    age INT NOT NULL CHECK (age >= 16 AND age <= 70),
    experience INT NOT NULL CHECK (experience >= 0),
    team_id INT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS teams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    commission INT NOT NULL,
    balance DECIMAL(10,2) DEFAULT 0
);
